# Generated by Django 4.2.4 on 2023-08-22 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateField(null=True)),
                ('Edited_Ip', models.GenericIPAddressField(null=True)),
                ('Title', models.CharField(max_length=500)),
                ('Thumbnail', models.ImageField(null=True, upload_to='gallery')),
                ('Total_Images', models.IntegerField(default=0)),
                ('Seo_Url', models.CharField(blank=True, max_length=500, null=True)),
                ('Seo_Title', models.CharField(blank=True, max_length=2000, null=True)),
                ('Seo_Description', models.TextField(blank=True, null=True)),
                ('Seo_Keywords', models.CharField(blank=True, max_length=2000, null=True)),
                ('AddedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_added_user', to=settings.AUTH_USER_MODEL)),
                ('EditedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_edited_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateField(null=True)),
                ('Edited_Ip', models.GenericIPAddressField(null=True)),
                ('Status', models.IntegerField(default=1)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(null=True, upload_to='images')),
                ('Phone', models.CharField(max_length=25, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Seo_Url', models.CharField(blank=True, max_length=500, null=True)),
                ('Seo_Title', models.CharField(blank=True, max_length=2000, null=True)),
                ('Seo_Description', models.TextField(blank=True, null=True)),
                ('Seo_Keywords', models.CharField(blank=True, max_length=2000, null=True)),
                ('AddedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_added_user', to=settings.AUTH_USER_MODEL)),
                ('EditedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_edited_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateField(null=True)),
                ('Edited_Ip', models.GenericIPAddressField(null=True)),
                ('Reference', models.CharField(max_length=25)),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(null=True, upload_to='images')),
                ('Designation', models.CharField(max_length=100)),
                ('Speciality', models.CharField(max_length=100)),
                ('Description', models.TextField(null=True)),
                ('Mobile', models.CharField(max_length=25)),
                ('AddedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_added_user', to=settings.AUTH_USER_MODEL)),
                ('Clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.clinic')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.department')),
                ('EditedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_edited_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(default=1)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100, null=True)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Course', models.CharField(max_length=100, null=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateField(null=True)),
                ('Edited_Ip', models.GenericIPAddressField(null=True)),
                ('Reference', models.CharField(max_length=25)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
                ('Deadline', models.DateField(null=True)),
                ('Job_Type', models.CharField(max_length=150, null=True)),
                ('Responsiblity', models.TextField(null=True)),
                ('Requirements', models.TextField(null=True)),
                ('Education', models.TextField(null=True)),
                ('Experiance', models.CharField(max_length=100, null=True)),
                ('Working_Time', models.CharField(max_length=100, null=True)),
                ('Working_Days', models.CharField(max_length=100, null=True)),
                ('Salary', models.CharField(max_length=100, null=True)),
                ('Vacancies', models.IntegerField(null=True)),
                ('AddedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wwu_added_user', to=settings.AUTH_USER_MODEL)),
                ('EditedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wwu_edited_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(default=1)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateField(null=True)),
                ('Edited_Ip', models.GenericIPAddressField(null=True)),
                ('Title', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(null=True, upload_to='images')),
                ('Seo_Url', models.CharField(blank=True, max_length=500, null=True)),
                ('Seo_Title', models.CharField(blank=True, max_length=2000, null=True)),
                ('Seo_Description', models.TextField(blank=True, null=True)),
                ('Seo_Keywords', models.CharField(blank=True, max_length=2000, null=True)),
                ('AddedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_added_user', to=settings.AUTH_USER_MODEL)),
                ('EditedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_edited_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Location1', models.CharField(max_length=100, null=True)),
                ('Message', models.TextField(null=True)),
                ('Sex', models.CharField(max_length=25, null=True)),
                ('Clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.clinic')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.department')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Album_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(upload_to='album_images')),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.album')),
            ],
        ),
    ]
