# Generated by Django 4.2.4 on 2023-08-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='Location1',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='Message',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='Sex',
        ),
    ]
