# Generated by Django 4.2.4 on 2023-08-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_appointments_location1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
