# Generated by Django 4.2.4 on 2023-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_appointments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.CharField(max_length=25)),
                ('Location', models.CharField(max_length=50, null=True)),
                ('CV', models.FileField(upload_to='files')),
            ],
        ),
    ]
