# Generated by Django 4.2.4 on 2023-08-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
