# Generated by Django 4.2.4 on 2023-08-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
