# Generated by Django 4.2.4 on 2023-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
