# Generated by Django 4.2.4 on 2023-08-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_department_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newslatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField(default=1)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
