# Generated by Django 4.2.4 on 2023-08-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_newslatter'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Seo_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='Seo_Keywords',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='Seo_Title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='Seo_Url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
