# Generated by Django 4.2.4 on 2023-08-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_department_seo_description_department_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='Hide',
            field=models.BooleanField(default=True),
        ),
    ]
