# Generated by Django 4.2.4 on 2023-08-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_career_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Mobile',
        ),
    ]
