# Generated by Django 4.2.4 on 2023-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_remove_doctor_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='Working_Time',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
