# Generated by Django 4.2.4 on 2023-08-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_clinic_working_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
