# Generated by Django 4.2.4 on 2023-08-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_remove_career_location_career_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
    ]
