# Generated by Django 4.2.4 on 2023-08-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_department_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='Hide',
            field=models.BooleanField(default=False),
        ),
    ]
