# Generated by Django 4.2.4 on 2023-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_alter_career_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=225)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
