# Generated by Django 4.2.4 on 2023-09-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_uploades'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploades',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
