# Generated by Django 4.2.4 on 2023-09-22 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_uploades_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploades',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
