# Generated by Django 4.2.4 on 2023-09-23 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_uploades_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Date',
            new_name='End_Date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Time',
            new_name='End_Time',
        ),
        migrations.AddField(
            model_name='event',
            name='Start_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Start_Time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
