# Generated by Django 4.2.4 on 2023-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_event_date_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='event',
            name='Venue',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
