# Generated by Django 4.2.4 on 2023-11-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0025_event_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="Location",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
