# Generated by Django 4.2.4 on 2023-11-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0027_remove_appointments_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="Doctor",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="Core.doctor",
            ),
            preserve_default=False,
        ),
    ]
