# Generated by Django 4.2.4 on 2023-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0031_contactformsubmission_remove_album_addedby_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="blog_images/")),
                ("seo_url", models.CharField(max_length=200)),
                ("seo_title", models.CharField(max_length=200)),
                ("seo_description", models.TextField()),
                ("seo_keywords", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("client_name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="project_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("Status", models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name="ContactFormSubmission",
        ),
    ]
