# Generated by Django 4.2.4 on 2023-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0032_blog_project_delete_contactformsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="Reference",
            field=models.CharField(default="ab", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="Status",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="project",
            name="Reference",
            field=models.CharField(default="ab", max_length=25),
            preserve_default=False,
        ),
    ]
