# Generated by Django 4.2.4 on 2023-11-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0033_blog_reference_blog_status_project_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="Added_Date",
            field=models.DateTimeField(auto_now_add=True, default="2002-02-02"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="Added_Date",
            field=models.DateTimeField(auto_now_add=True, default="2023-09-08"),
            preserve_default=False,
        ),
    ]
