# Generated by Django 4.2.4 on 2023-11-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0034_blog_added_date_project_added_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("Status", models.IntegerField(default=1)),
                ("Reference", models.CharField(max_length=25)),
                ("Added_Date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
