# Generated by Django 4.2.4 on 2023-11-15 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Frontpage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactFormSubmission",
        ),
    ]
